name: sample_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  equatable: ^2.0.0
  rxdart: ^0.27.1
  get_it: ^7.1.3
  flutter_spinkit: ^5.0.0
  cupertino_icons: ^1.0.2
  data:
    path: data

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/cfg/
    - assets/locale/
    - assets/images/svg/
    - assets/data/